export default {
    id: null,
    isActive: false,
    description: null,
    count: null,
    isForChild: false,
    isMale: false,
    isFemale: false,
    isUnisex: false,
    product: null,
    selectedRentalPointId: null,
    productList: [],
    selectedProductId: null,
    categoryList: [],
    selectedCategoryId: null,
};